config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get '/rules', to: 'pages#rules', as: :rules

  resources :cards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  CREATORS = %w(Lap Boat Beer)
  STATUSES = %w(draft printed approved modify_needed rejected)
  TYPES    = %w(event_jungle event_town item_help item_poke)

  validates_presence_of :title, :description, :creator, :status, :card_type

  after_create :add_running_number

  private

  def add_running_number
    last_running_number = Card
                            .where.not(running_number: nil)
                            .order(running_number: :desc)
                            .first
                            .running_number
    update running_number: last_running_number + 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :load_card, except: :index

  def index
    @cards = Card.order(id: :asc)
    @card_counts = Card.group(:card_type).count.sort_by(&:last)
  end

  def new
  end

  def create
    if @card.update(card_params)
      redirect_to cards_path, notice: 'Card created!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @card.update(card_params)
      redirect_to cards_path, notice: 'Card update!'
    else
      render :edit
    end
  end

  def destroy
    if @card.destroy
      redirect_to cards_path, notice: 'Card deleted!'
    else
      render :new
    end
  end

  private

  def load_card
    if params[:id]
      @card = Card.find(params[:id])
    else
      @card = Card.new(status: 'draft')
    end
  end

  def card_params
    params.require(:card).permit!
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @cards = Card.order(created_at: :desc).first(6)
  end

  def rule
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
  TYPES = {
    event_jungle: {
      text: 'อีเว้นท์ป่า',
      icon: 'paw'
    },
    event_town: {
      text: 'อีเว้นท์เมือง',
      icon: 'home'
    },
    item_help: {
      text: 'ไอเท็มรักษา',
      icon: 'flask'
    },
    item_poke: {
      text: 'ไอเท็มกลั่นแกล้ง',
      icon: 'map-signs'
    }
  }

  STATUSES = {
    draft: 'secondary',
    printed: 'info',
    approved: 'success',
    modify_needed: 'warning',
    deleted: 'danger'
  }

  def card_type_icons(type, klass=nil)
    TYPES.map do |key, value|
      card_type_icon(key, "#{klass} #{'d-none' if type.try(:to_sym) != key}")
    end.join("\n").html_safe
  end

  def card_type_icon(type, klass= nil)
    content_tag :i,
                '',
                class: "fa fa-#{TYPES[type.to_sym][:icon]} #{klass}",
                data: { value: type }
  end

  def card_type_name(type)
    if type
      TYPES[type.to_sym].try(:[], :text)
    end
  end

  def card_status(status)
    content_tag :span,
                status.titleize,
                class: "badge badge-#{STATUSES[status.to_sym]}"
  end

  def card_type_collection
    TYPES.map { |key, value| [ value[:text], key] }
  end
end

app/views/cards/_card.html.erb
<div class="card-container" id="card-<%= card.id %>">
  <% unless local_assigns[:disabled_action] %>
    <div class="row">
      <div class="col-6">
        <%= card_status card.status %>
      </div> <!-- .col-9 -->

      <div class="col-6 text-right">
        <% if card.note.present? %>
          <div class="d-inline-block" style="line-height: 24px; vertical-align: middle;margin-right: 8px; font-size: 24px;">
            <i  class="fa fa-comments"
                style="cursor: pointer"
                data-toggle="popover"
                data-placement="bottom"
                title="Comment"
                data-container="#card-<%= card.id %>"
                data-content="<%= card.note %>">
            </i> <!-- .fa fa-comments -->
          </div> <!-- .d-inline-block -->
        <% end %>

        <div class="dropdown d-inline-block">
          <a href="#" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-fw fa-cog"></i> <!-- .fa fa-comments -->
          <a>

          <div class="dropdown-menu dropdown-menu-right">
            <%= link_to edit_card_path(card), class: 'dropdown-item' do %>
              <small>Edit Card</small>
            <% end %>

            <%= link_to card_path(card), class: 'dropdown-item', data: { confirm: 'Are you sure to delete?' }, method: 'delete' do %>
              <small>Delete Card</small>
            <% end %>
          </div> <!-- .dropdown-menu -->
        </div> <!-- .dropdown d-inline-block -->
      </div> <!-- .col-3 -->
    </div> <!-- .row -->
  <% end %>

  <div class="card <%= card.card_type %>">
    <%= card_type_icon card.card_type, 'card-image-placeholder' %>
    <div class="card-title"><%= card.title %></div> <!-- .card-title -->
    <div class="card-description"><%= card.description %></div> <!-- .card-description -->
    <div class="card-type-icon"><%= card_type_icon(card.card_type) %></div> <!-- .pull-right -->
  </div> <!-- .card -->

  <div class="row card-creator-detail">
    <div class="col-7">
      <small class="text-muted">Created by</small> <!-- .text-muted -->
      <strong><%= card.creator %></strong>
    </div> <!-- .col-7 -->
    <div class="col-5 text-right">
      <small class="text-muted">ID#<%= '%05d' % card.running_number %></small> <!-- .text-muted -->
    </div> <!-- .col-5 -->
  </div> <!-- .row -->
</div> <!-- .card-container -->

app/views/cards/_form.html.erb
<% if @card.errors.any? %>
  <div class="alert alert-danger">
    <%= @card.errors.full_messages.join("<br>").html_safe %>
  </div> <!-- .alert alert-danger -->
<% end %>

<%= form_for @card, { html: { class: 'card-form' } } do |f| %>
  <div class="row">
    <div class="col-12 col-sm-12 col-md-6 col-lg-4 offset-lg-2">
      <div class="card-container">
        <div class="card <%= @card.card_type %>">
          <%= f.text_field :title, class: 'card-title' %>
          <div class="card-type-icon">
            <%= card_type_icons(@card.card_type) %>
          </div> <!-- .card-type -->

          <i class="fa fa-photo card-image-placeholder"></i> <!-- .fa fa-photo card-image-placholder -->
          <%= card_type_icons @card.card_type, 'card-image-placeholder' %>

          <%= f.text_area :description, class: 'card-description' %>
        </div> <!-- .card -->
      </div> <!-- .card-container -->
    </div> <!-- .col-12 col-sm-6 -->

    <div class="col-12 col-sm-12 col-md-6 col-lg-4">
      <div class="card-container">
        <div class="d-inline-block" style="margin: 4px 8px 0 0;width: 110px">Card status:</div> <!-- .pull-left -->
        <div class="dropdown d-inline-block">
          <a href="#" class="js--btn-card-status btn btn-light btn-sm dropdown-toggle" data-toggle="dropdown" style="width: 160px">
            <span class="text">
              <%= @card.status.titleize %>
            </span> <!-- .text -->
          </a> <!-- .btn-default btn-sm -->

          <div class="js--card-status-dropdown dropdown-menu">
            <% Card::STATUSES.each do |value| %>
              <a href="#" class="dropdown-item js--card-status-selector" data-value="<%= value %>" %><%= value.titleize %></a>
            <% end %>
          </div> <!-- .dropdown-menu -->
        </div> <!-- .dropdown -->
        <%= f.hidden_field :status %>

        <div class="d-inline-block" style="margin: 4px 8px 0 0;width: 110px">Card type:</div> <!-- .pull-left -->
        <div class="dropdown d-inline-block">
          <a href="#" class="js--btn-card-type btn btn-light btn-sm dropdown-toggle" data-toggle="dropdown" style="width: 160px">
            <span class="text">
              <% if @card.card_type.present? %>
                <%= card_type_name @card.card_type %>
              <% else %>
                - Please Select -
              <% end %>
            </span> <!-- .text -->
          </a> <!-- .btn-default btn-sm -->

          <div class="js--card-type-dropdown dropdown-menu">
            <% card_type_collection.each do |text, value| %>
              <a href="#" class="dropdown-item js--card-type-selector" data-value="<%= value %>" %><%= text %></a>
            <% end %>
          </div> <!-- .dropdown-menu -->
        </div> <!-- .dropdown -->
        <%= f.hidden_field :card_type %>

        <div class="d-inline-block" style="margin: 4px 8px 0 0;width: 110px">Creator:</div> <!-- .pull-left -->
        <div class="dropdown d-inline-block">
          <a href="#" class="js--btn-card-creator btn btn-light btn-sm dropdown-toggle" data-toggle="dropdown" style="width: 160px;">
            <span class="text">
              <% if @card.creator.present? %>
                <%= @card.creator %>
              <% else %>
                - Please Select -
              <% end %>
            </span> <!-- .text -->
          </a> <!-- .btn-default btn-sm -->

          <div class="js--card-creator-dropdown dropdown-menu">
            <% Card::CREATORS.each do |value| %>
              <a href="#" class="dropdown-item js--card-creator-selector" data-value="<%= value %>" %><%= value %></a>
            <% end %>
          </div> <!-- .dropdown-menu -->
        </div> <!-- .dropdown -->
        <%= f.hidden_field :creator %>

        <hr>
        <div class="form-group">
          Comments:<br>

          <%= f.text_area :note, class: 'card-note' %>
        </div> <!-- .form-group -->

        <div style="margin: 15px 0;">
          <div class="row">
            <div class="col-sm-6 col-12">
              <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>
              <div style="height: 8px"></div>
            </div> <!-- .col-sm-6 col-xs-12 -->

            <div class="col-sm-6 col-12">
              <%= link_to 'Back', cards_path, class: 'btn btn-light btn-block' %>
              <div style="height: 8px"></div>
            </div> <!-- .col-sm-6 col-xs-12 -->
          </div> <!-- .row -->
        </div>
      </div> <!-- .card-container -->
    </div> <!-- .col-12 col-sm-6 -->
  </div> <!-- .row -->
<% end %>

app/views/cards/edit.html.erb
<br>
<div class="container">
  <h2>Edit Card</h2>
  <hr>
  <%= render 'form' %>
</div> <!-- .container -->

app/views/cards/index.html.erb
<br>
<div class="container">
  <div class="pull-right" style="margin-top: 5px;">
    <%= link_to new_card_path, class: 'btn btn-primary btn-sm' do %>
      <i class="fa fa-plus"></i> <!-- .fa fa-plus -->
      Add New Card
    <% end %>
  </div> <!-- .pull-right -->

  <h2>Cards</h2>
    <div class="row">
    <div class="col-12 col-sm-6 text-muted text-center text-sm-left">
      <strong>Total : <%= pluralize @card_counts.sum(&:last), 'card' %></strong>
      <div style="height:5px" class="d-block d-sm-none"></div>
    </div> <!-- .col-12 col-sm-6 -->

    <div class="col-12 col-sm-6 text-center text-sm-right">
      <% @card_counts.each do |key, count|%>
        <span class="<%= key%>" style="margin: 0 8px;"><%= card_type_icon key%> : <%= count %></span>
      <% end %>
    </div> <!-- .col-12 col-sm-6 -->
  </div>

  <hr>

  <div class="row">
    <% @cards.each do |card| %>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
        <%= render partial: 'cards/card', object: card %>
      </div> <!-- .col-xs-12 col-sm-12 col-md-6 col-lg-4 -->
    <% end %>
  </div> <!-- .row -->
</div> <!-- .container -->

app/views/cards/new.html.erb
<br>
<div class="container">
  <h2>Add New Card</h2>
  <hr>
  <%= render 'form' %>
</div> <!-- .container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Law Of Jungle | DB</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_include_tag 'application' %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Kanit:300&amp;subset=thai" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link_to 'LAW OF JUNGLE DB', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="main-nav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item <%= 'active' if current_page?(rules_path) %>">
              <%= link_to 'RULES', rules_path, class: 'nav-link' %></li>
            </li>
            <li class="nav-item <%= 'active' if current_page?(controller: :cards) %>">
              <%= link_to 'CARDS', cards_path, class: 'nav-link' %>
            </li>
          </ul> <!-- .nav navbar-nav navbar-right -->
        </div>
      </div> <!-- .container -->
    </nav> <!-- .nav navbar-default -->

    <%= yield %>
    <div style="height: 25px"></div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron">
  <div class="container text-center">
    <h1 class="display-4">
      <i class="fa fa-map-signs"></i>
      <br>
      LAW OF JUNGLE!
    </h1>

    <hr>

    <h4 class="text-muted">From city to jungle ... finding for GOLDEN EGG !!</h4>
    <br>
    <div class="text-center">
      <%= link_to new_card_path, class: 'btn btn-lg btn-primary' do %>
        <i class="fa fa-plus"></i> <!-- .fa fa-plus -->
        Add New Card
      <% end %>
    </div> <!-- .text-center -->
  </div> <!-- .container -->
</div> <!-- .jumbotron -->

<div class="container">
  <h2>
    Recent Cards
    <div class="pull-right">
      <%= link_to 'View All', cards_path, class: 'btn btn-link' %>
    </div> <!-- .pull-right -->
  </h2>
  <hr>

  <div class="row">
    <% @cards.each do |card| %>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
        <%= render partial: 'cards/card', object: card, locals: { disabled_action: true } %>
      </div> <!-- .col-xs-12 col-sm-12 col-md-6 col-lg-4 -->
    <% end %>
  </div> <!-- .row -->
</div> <!-- .container -->

<%# TODO: Render latest card. %>

app/views/pages/rules.html.erb
<br><br><br>
<h1 class="display-3 text-center">
  <i class="fa fa-book"></i> <!-- .fa fa-book -->
  <br>
  Comming soon...
</h1> <!-- .display-5 -->

<h3 class="text-muted text-center">
  ทำไม่ทันโว้ย
</h3> <!-- .text-muted -->